<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<NoWarn>NU1701</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
		<PackageReference Include="ReactiveUI.WPF" Version="20.4.1" />
		<!-- levelDB数据库 -->
		<PackageReference Include="LevelDB.Standard" Version="2.1.6.1" />
		<!-- EF Core -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
		<!-- 依赖注入 -->
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<!-- Everything64.dll：复制到输出目录 -->
	<ItemGroup>
		<Content Include="Everything64.dll" Condition="Exists('Everything64.dll')">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<Content Include="Zhou.LevelDB.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>